on:
  workflow_dispatch:

jobs: 
  hercules-charts:
   runs-on: ubuntu-latest
   name: Hercules Insights
   steps:
     - uses: actions/checkout@master
       with:
          fetch-depth: 0
     - name: Hercules
       uses: src-d/hercules@v10.7.2
       with:
          args: --burndown
     - uses: actions/upload-artifact@master
       with:
          name: hercules_charts
          path: hercules_charts.tar
